### ISSUE TITLE
Composer install won't finish

### ISSUE THREAD

**Issue by bonswouar** [servergrove/ansible-symfony2#19]
From the last master version.

When it runs `ansible-symfony2 | Run composer install.`, it never ends.

I think (but I might be wrong?) it's because of the prompt asking for params (or use default ones).

Here is the `-vvv` debug :
```
REMOTE_MODULE command cd /home/www/git/proj/releases/20150610111810 && export SYMFONY_ENV=prod && php /home/www/git/proj/composer.phar install --no-dev --optimize-autoloader #USE_SHELL
```

And when I run it outside of Ansible I get the prompt asking for :
```
Some parameters are missing. Please provide them.
secret (ThisTokenIsNotSoSecretChangeIt): 
```

**Comment by maschmann** [comment]
Hi bonswouar,

that's right: Will investigate later tonight. Strangely this did not occur during the sf2 default install (at least according to the last travis test). Maybe a change in the sf2 installation?
check: https://travis-ci.org/servergrove/ansible-symfony2

The parameters are processed when there is no parameters.ini and only a parameters.dist file, but I'm not sure why the interactive shell is popping up at that point.

And: Thanks for reporting :+1:

**Comment by maschmann** [comment]
@bonswouar : I tried it locally with current 2.6 and 2.7 versions of symfony and the paramerters.yml gets created. Do you have any specialities in your deployment?
What environment do you use?  sf version?

**Comment by bonswouar** [comment]
Thank you for your investigation @maschmann !

Actually yes, I have some specialities in my deployment.. I use [Incenteev/ParameterHandler](https://github.com/Incenteev/ParameterHandler) to handle multiple parameter files.
Precisely, I've got 3 `parameters.yml` files with that configuration in `composer.json` :
```yml
        "incenteev-parameters": [{
            "file": "apps/config/common_parameters.yml"
        },
        {
            "file": "apps/app1/config/parameters.yml"
        },
        {
            "file": "apps/app2/config/parameters.yml"
        }]
```
But it shouldn't change the behaviour of composer handling those `.dist` files ?!

**Comment by maschmann** [comment]
@bonswouar that's actually triggered by the composer post-install/upgrade hook:

```json
    "scripts": {
        ...
        "post-install-cmd": [
            "Incenteev\\ParameterHandler\\ScriptHandler::buildParameters",
            ...
        ],
        "post-update-cmd": [
            "Incenteev\\ParameterHandler\\ScriptHandler::buildParameters",
            ...
        ]
    },
    "extra": {
        ...
        "incenteev-parameters": {
            "file": "app/config/parameters.yml"
        },
        ...
    }
```
But it's only framework-stuff triggered by the install/update.
During further research, I found a mentioning of non-interactive mode for composer [here](https://github.com/Incenteev/ParameterHandler) and as params [here](https://getcomposer.org/doc/03-cli.md#composer-no-interaction). I'll integrate into composer calls and test :-)
As far as I know, the interactive mode shouldn't be triggered if env > dev. Which env are you deploying?
