### ISSUE TITLE
Default value of "symfony2_project_composer_opts" is wrong for DEV environment

### ISSUE THREAD

**Issue by zanardigit** [servergrove/ansible-symfony2#25]
The default value for `symfony2_project_composer_opts` is 

    '--no-dev --optimize-autoloader --no-interaction'

but this value produces an error if `symfony2_project_env` is set to **dev**.

Of course I can force the value in my deploy.yml, but I was wondering if it's possible to programmatically change the default value for `symfony2_project_composer_opts` according to the set value of `symfony2_project_env`. 

I am a beginner with Ansible so I can't suggest a solution.

**Comment by zanardigit** [comment]
See also http://serverfault.com/questions/715769/ansible-change-default-value-according-to-a-condition/715772#715772

**Comment by maschmann** [comment]
@zanardigit I think this has to be done within the role - use your deployment config as a workaround until I can provide a solution. I'm planning to restructure the deployment in the next few weeks while I refactor my deployments @ work :-)

**Comment by zanardigit** [comment]
No rush! I just wanted to suggest an improvement. Hopefully I will be able to provide a PR myself.
