### ISSUE TITLE
Local Cache Folder

### ISSUE THREAD

**Issue by blackstar257** [servergrove/ansible-symfony2#39]
How do you folks usually deal with permissions around the cache folder? I created my own "hook" file currently to do the chmod.

**Comment by maschmann** [comment]
That's what id' suggest, too - normally the directory permissions should be set within your repository (cache/.gitkeep). If you're using php-fpm, there should be no permission problem, since the php-fpm user should own the whole vhost dir :-)

**Comment by blackstar257** [comment]
Thanks
