### ISSUE TITLE
Is master branch usable to deploy sf3.3/3.4 in production ?

### ISSUE THREAD

**Issue by zneel** [servergrove/ansible-symfony2#46]
Is this project still maintained and suitable to deploy SF3.3/3.4 projects in production? 
I tried ansistrano but I didn't managed to do it easily with the handling/hooks of symlinks of the shared folder on iSCSI shared disks..
Thanks in advance.

**Comment by pgodel** [comment]
@zneel I would suggest you look at https://ansistrano.com/ which does everything this project used to do and more.

**Comment by zneel** [comment]
@pgodel Thank you very much sir!
