### ISSUE TITLE
First execution throws error for creating link to source file

### ISSUE THREAD

**Issue by richhl** [servergrove/ansible-symfony2#5]
following instruction here: http://blog.servergrove.com/2014/04/01/deployment-symfony2-applications-ansible/

i got this error:

failed: [localhost] => {"failed": true, "item": "", "path": "/home/myproject/master/releases/1/app/logs", "src": "/home/myproject/master/shared/app/logs", "state": "absent"}
msg: src file does not exist, use "force=yes" if you really want to create the link: /home/myproject/master/shared/app/logs

when executing: ansible-playbook -l prod -i app/config/hosts.ini -e "symfony2_project_release=1" app/config/deploy.yml -vvv --check

thx in advance

**Comment by maectpo** [comment]
> (actually, to have them there is a mistake)

I should not agree with you. When you create new project through the Composer the folders exist with .gitkeep files. Deleting them is kind a dirty hack.

Is there any other workaround?

**Comment by maschmann** [comment]
@maectpo  I don't consider it a dirty hack - having the log and cache folders in the symfony distribution is just a convention and therefore I don't see it as a dirty hack to change the folders.
Having them in a symfony standard project keeps the project from having more directory checks/creations.
