### ISSUE TITLE
Refusing to convert between directory and link 

### ISSUE THREAD

**Issue by aardudvtm** [servergrove/ansible-symfony2#52]
Running the ansible-symfony2 playbook gives me an error while creating a symlink for release.

 FAILED! => {"changed": false, "gid": 33, "group": "www-data", "mode": "0774", "msg": "refusing to convert between directory and link for /var/www/my.app.com/current", "owner": "www-data", "path": "/var/www/my.app.com/current", "size": 4096, "state": "directory", "uid": 33}

I have removed app/logs and app/cache from my repo but its still not working. I currently have no clue how to proceed.

**Comment by servergrove** [comment]
servergrove/ansible-symfony2,


Thank you for contacting our support team. A support ticket has now been opened for your request. You will be notified when a response is made by email. The details of your ticket are shown below.


Subject: [servergrove/ansible-symfony2] Refusing to convert between directory and link  (#52)
Priority: Medium
Status: Open


You can view the ticket at any time at https://secure.servergrove.com/clients/viewticket.php?tid=484935&c=9E1hHCCs

**Comment by servergrove** [comment]
servergrove/ansible-symfony2,


Thank you for contacting our support team. A support ticket has now been opened for your request. You will be notified when a response is made by email. The details of your ticket are shown below.


Subject: [servergrove/ansible-symfony2] Refusing to convert between directory and link  (#52)
Priority: Medium
Status: Open


You can view the ticket at any time at https://secure.servergrove.com/clients/viewticket.php?tid=312865&c=GzgWBJTI

**Comment by servergrove** [comment]
servergrove/ansible-symfony2,


Thank you for contacting our support team. A support ticket has now been opened for your request. You will be notified when a response is made by email. The details of your ticket are shown below.


Subject: Re: [servergrove/ansible-symfony2] Refusing to convert between directory and link  (#52)
Priority: Medium
Status: Open


You can view the ticket at any time at https://secure.servergrove.com/clients/viewticket.php?tid=152403&c=wiymUxQk

**Comment by servergrove** [comment]
servergrove/ansible-symfony2,


Thank you for contacting our support team. A support ticket has now been opened for your request. You will be notified when a response is made by email. The details of your ticket are shown below.


Subject: Re: [servergrove/ansible-symfony2] Refusing to convert between directory and link  (#52)
Priority: Medium
Status: Open


You can view the ticket at any time at https://secure.servergrove.com/clients/viewticket.php?tid=399921&c=H5mdSVRL
